[2024-12-05 22:53:48,791] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:30,042] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.73:5000 - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:30,043] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:38,525] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:38] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:38,533] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:38] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:38,827] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:38] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:40,143] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:40] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:40,188] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:40] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:40,387] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:40] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:40,494] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:40] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:40,907] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:40] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:52,105] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:52] "GET /lista?id=3 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:52,107] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:52] "GET /produtos?id_lista=3 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:55:58,815] WARNING add_produto() L67   Erro ao adicionar produto 'teste', Produto de mesmo nome já salvo na base :/ - call_trace=D:\Tiago\PUCRio\slc-mvp\slc_api\app.py L67  
[2024-12-05 22:55:58,816] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:55:58] "[31m[1mPOST /produto HTTP/1.1[0m" 409 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:28,680] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.73:5000 - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:28,681] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:37,354] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:37] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:37,420] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:37] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:37,605] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:37] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:37,680] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:37] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:38,065] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:38] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:38,067] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:38] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:44,996] WARNING get_lista() L199  Erro ao buscar lista '3', Lista não encontrado na base :/ - call_trace=D:\Tiago\PUCRio\slc-mvp\slc_api\app.py L199 
[2024-12-05 22:56:45,009] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:45] "[33mGET /lista?id=3 HTTP/1.1[0m" 404 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:45,018] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:45] "GET /produtos?id_lista=3 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:48,647] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:48] "GET /listas HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:56:57,029] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:56:57] "POST /lista HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:57:01,455] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:57:01] "GET /lista?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:57:01,484] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:57:01] "GET /produtos?id_lista=1 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:57:10,755] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:57:10] "POST /produto HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:57:24,332] WARNING add_produto() L67   Erro ao adicionar produto 'teste', Produto de mesmo nome já salvo na base :/ - call_trace=D:\Tiago\PUCRio\slc-mvp\slc_api\app.py L67  
[2024-12-05 22:57:24,333] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:57:24] "[31m[1mPOST /produto HTTP/1.1[0m" 409 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:57:31,480] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:57:31] "POST /produto HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:58:00,919] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:58:00] "GET /listas HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:58:03,410] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:58:03] "GET /lista?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:58:03,448] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:58:03] "GET /produtos?id_lista=1 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:58:22,970] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:58:22] "POST /produto HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:58:29,196] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:58:29] "GET /lista?id=1 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:58:29,212] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:58:29] "GET /produtos?id_lista=1 HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-05 22:58:43,782] INFO _log() L97   127.0.0.1 - - [05/Dec/2024 22:58:43] "GET /listas HTTP/1.1" 200 - - call_trace=C:\Users\tiago\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\_internal.py L97  
